#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_svg_animation.py — cute_dog.svg ko ek SELF-CONTAINED animated SVG me badal do.

Ye file browser me directly chalti hai (koi Python/ffmpeg nahi chahiye):
    xdg-open cute_dog_animated.svg      ya    drag into Chrome

Kya-kya animate hota hai (SMIL <animateTransform>):
    body  = squash/stretch breathing + bounce      head = bob + tilt
    ears  = flop                                   tail = wag (fast jab khushi)
    eyes  = blink                                  caption = typewriter underline
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from make_animation import load_svg          # same parser, no duplication

OUT = os.path.join(HERE, "cute_dog_animated.svg")
SRC = os.path.abspath(os.path.join(HERE, "..", "cute_dog.svg"))

# part -> (kind, pivot, values) ; kind: rotate | scale | translate
RIG = {
    "Body":                 ("scale",    (100, 225), "1 1;1.03 0.97;1 1",                          "3.2s"),
    "Belly spot":           ("scale",    (100, 225), "1 1;1.03 0.97;1 1",                          "3.2s"),
    "Head":                 ("rotate",   (100, 122), "-4 100 122;4 100 122;-4 100 122",           "2.6s"),
    "Snout":                ("rotate",   (100, 122), "-4 100 122;4 100 122;-4 100 122",           "2.6s"),
    "Nose":                 ("rotate",   (100, 122), "-4 100 122;4 100 122;-4 100 122",           "2.6s"),
    "Mouth":                ("rotate",   (100, 122), "-4 100 122;4 100 122;-4 100 122",           "2.6s"),
    "Happy expression (tongue)": ("rotate", (100, 122), "-4 100 122;4 100 122;-4 100 122",        "2.6s"),
    "Left Ear":             ("rotate",   (70, 18),   "-9 70 18;7 70 18;-9 70 18",                  "1.35s"),
    "Right Ear":            ("rotate",   (130, 18),  "7 130 18;-9 130 18;7 130 18",                "1.35s"),
    "Left Eye":             ("follow",   None, None, None),
    "Right Eye":            ("follow",   None, None, None),
    "Tail":                 ("rotate",   (145, 132), "-16 145 132;16 145 132;-16 145 132",        "0.42s"),
    "Left Front Paw":       ("rotate",   (82, 192),  "-6 82 192;6 82 192;-6 82 192",               "1.6s"),
    "Right Front Paw":      ("rotate",   (117, 192), "6 117 192;-6 117 192;6 117 192",             "1.6s"),
}
EYE_PIVOT = {"Left Eye": (85, 70), "Right Eye": (115, 70)}


def esc(txt):
    return (txt.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def shape_tag(e):
    """Re-emit the original primitive (smaller file, same look as the source SVG)."""
    return e


def build():
    vb, els = load_svg(SRC)
    src = open(SRC, encoding="utf-8").read()
    # original primitives grouped under their <!-- comment --> name
    groups, part = {}, "misc"
    for raw in src.splitlines():
        line = raw.strip()
        cm = re.match(r"<!--\s*(.*?)\s*-->", line)
        if cm:
            part = cm.group(1)
            groups.setdefault(part, [])
            continue
        mm = re.match(r"<(circle|ellipse|rect|path)\b.*?/?>", line)
        if mm:
            groups.setdefault(part, []).append('      ' + mm.group(0))

    W, H = 1080, 1350
    sc = 3.2                 # svg units -> canvas px
    dog_cx, dog_cy = W / 2, 660        # character anchor (its svg point 100,120)
    ox, oy = dog_cx - 100 * sc, dog_cy - 120 * sc
    feet_y = dog_cy + 116 * sc

    out = []
    A = out.append
    A('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 %d %d" width="1080" height="%d" '
      'preserveAspectRatio="xMidYMid meet" font-family="Noto Sans Devanagari, Nirmala UI, Mukta, sans-serif">' % (W, H, H))
    A('  <!-- AUTO-GENERATED by make_svg_animation.py from cute_dog.svg. Open in a browser: it just runs. -->')
    A('  <defs>')
    A('    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">'
      '<stop offset="0" stop-color="#0f1117"/><stop offset="1" stop-color="#1a1d29"/></linearGradient>')
    A('    <radialGradient id="glow" cx="0.5" cy="0.42" r="0.6">'
      '<stop offset="0" stop-color="#ffd700" stop-opacity="0.30"/>'
      '<stop offset="1" stop-color="#ffd700" stop-opacity="0"/></radialGradient>')
    A('    <linearGradient id="accent" x1="0" y1="0" x2="1" y2="0">'
      '<stop offset="0" stop-color="#ffd700"/><stop offset="1" stop-color="#00d4aa"/></linearGradient>')
    A('    <filter id="soft" x="-30%" y="-30%" width="160%" height="160%">'
      '<feGaussianBlur stdDeviation="14"/></filter>')
    A('  </defs>')
    A('  <rect width="%d" height="%d" fill="url(#bg)"/>' % (W, H))
    A('  <rect width="%d" height="%d" fill="url(#glow)"/>' % (W, H))
    # faint drifting paw prints
    A('  <g fill="#ffd700" opacity="0.16">')
    for k, (px, py, s) in enumerate([(120, 420, 16), (950, 560, 20), (150, 1050, 18), (930, 1150, 14), (880, 250, 12)]):
        A(f'    <g transform="translate({px},{py})"><circle r="{s*0.55}" cy="{s*0.3}"/>'
          f'<circle r="{s*0.26}" cx="{s*0.55}" cy="-{s*0.35}"/><circle r="{s*0.26}" cx="-{s*0.55}" cy="-{s*0.35}"/>'
          f'<circle r="{s*0.24}" cx="{s*0.2}" cy="-{s*0.72}"/><circle r="{s*0.24}" cx="-{s*0.2}" cy="-{s*0.72}"/>'
          f'<animateTransform attributeName="transform" additive="sum" type="translate" '
          f'values="0 0; 0 -34; 0 0" dur="{6 + k}s" repeatCount="indefinite"/></g>')
    A('  </g>')

    # title (typewriter reveal)
    A(f'  <text x="{W/2}" y="112" text-anchor="middle" font-size="58" font-weight="800" fill="#ffd700">छोटा शेरू, बड़ी एनिमेशन</text>')
    A(f'  <rect x="{W/2-180}" y="136" width="360" height="6" rx="3" fill="url(#accent)">'
      '<animate attributeName="width" values="0;360" dur="1.1s" fill="freeze"/></rect>')
    A(f'  <text x="{W/2}" y="180" text-anchor="middle" font-size="26" fill="#9ca3af">'
      'ye poori animation sirf ek &lt;g&gt; + &lt;animateTransform&gt; se bani hai</text>')

    # ground shadow
    A(f'  <ellipse cx="{W/2}" cy="{feet_y}" rx="150" ry="26" fill="#000" opacity="0.42" filter="url(#soft)">'
      '<animate attributeName="rx" values="150;132;150" dur="3.2s" repeatCount="indefinite"/></ellipse>')

    # ---- character: whole-body bounce
    A('  <g transform="translate(%.1f,%.1f) scale(%s) translate(-100,-120)">' % (ox, oy, sc))
    A('    <animateTransform attributeName="transform" additive="sum" type="translate" '
      'values="0 0; 0 -26; 0 0" dur="1.6s" repeatCount="indefinite" calcMode="spline" '
      'keySplines="0.3 0 0.2 1; 0.5 0 0.5 1" keyTimes="0;0.45;1"/>')
    for part, shapes in groups.items():
        if not shapes:
            continue
        kind, pivot, values, dur = RIG.get(part, ("none", None, None, None))
        if kind == "none" and part not in EYE_PIVOT:
            A("    <g>%s</g>" % (" ".join(s.strip() for s in shapes)))
            continue
        if kind == "rotate":
            inner = ('<animateTransform attributeName="transform" type="rotate" values="%s" dur="%s" '
                     'repeatCount="indefinite" calcMode="spline" keyTimes="0;0.5;1" '
                     'keySplines="0.4 0 0.6 1;0.4 0 0.6 1"/>' % (values, dur))
            A('    <g transform="translate(0,0)">%s\n%s</g>' % (inner, "\n".join(shapes)))
        elif kind == "scale":
            px, py = pivot
            inner = ('<g transform="translate(%g,%g)"><g transform="translate(%g,%g)">'
                     '<animateTransform attributeName="transform" type="scale" values="%s" dur="%s" '
                     'repeatCount="indefinite"/>%s</g></g>' % (px, py, -px, -py, values, dur,
                                                               "\n".join(shapes).replace("      ", "        ")))
            A('    ' + inner)
        elif part in EYE_PIVOT:
            px, py = EYE_PIVOT[part]
            A('    <g transform="translate(%g,%g)"><g transform="translate(%g,%g)">'
              '<animateTransform attributeName="transform" type="scale" '
              'values="1 1;1 1;1 0.08;1 1;1 1" keyTimes="0;0.40;0.45;0.50;1" dur="4.1s" '
              'repeatCount="indefinite"/>%s</g></g>'
              % (px, py, -px, -py, "\n".join(shapes).replace("      ", "        ")))
    A('  </g>')

    # captions cycling
    caps = ["पूंछ हिलती है = खुशी का signal",
            "कान फड़फड़ाते हैं, सिर हल्का tilted रहता है",
            "हर shape एक &lt;ellipse&gt;/&lt;path&gt; है, हर part अपने &lt;g&gt; में"]
    A('  <g font-size="38" font-weight="700" fill="#e8e8e8" text-anchor="middle">')
    n = len(caps)
    for i, c in enumerate(caps):
        a0, a1 = i / n, (i + 1) / n
        if i == 0:
            vals, kt = "1;0", f"0;{a1:.3f}"
        elif i == n - 1:
            vals, kt = "0;1", f"0;{a0:.3f}"
        else:
            vals, kt = f"0;1;0", f"0;{a0:.3f};{a1:.3f}"
        A(f'    <text x="{W/2}" y="{H-150}" opacity="0">{esc(c)}'
          f'<animate attributeName="opacity" calcMode="discrete" values="{vals}" keyTimes="{kt}" '
          f'dur="{n*3.0}s" repeatCount="indefinite"/></text>')
    A('  </g>')
    A(f'  <text x="{W/2}" y="{H-60}" text-anchor="middle" font-size="24" fill="#6b7280">'
      'loop: repeatCount="indefinite" · timing: dur/keyTimes · no video editor needed</text>')
    A('</svg>')
    open(OUT, "w", encoding="utf-8").write("\n".join(out))
    print("wrote", OUT, os.path.getsize(OUT), "bytes")


if __name__ == "__main__":
    build()
